modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This specifies Forge 43.x.x and above.
license="MIT" # Replace this with your actual license.
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId="bludphenomenon" # Replace this with your actual mod id.
version="1.0.0" # Replace this with your actual mod version.
displayName="Blud Phenomenon" # Replace this with your actual mod name.
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="Your Name" # Replace this with your actual name.
#displayTest="MATCH_VERSION" #optional

description='''
This mod contains high volume sounda and violence.
'''

[[dependencies.bludphenomenon]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[43,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.bludphenomenon]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]" # This specifies Minecraft 1.19.2.
ordering="NONE"
side="BOTH"