modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This specifies Forge 43.x.x and above.
license="MIT" # Replace this with your actual license.
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://example.com/issues" #optional

[[mods]] #mandatory
modId="bludmod" # Replace this with your actual mod id.
version="1.0.0" # Replace this with your actual mod version.
displayName="Blud Phenomenon" # Replace this with your actual mod name.
#updateJSONURL="https://example.com/updates.json" #optional
#displayURL="https://example.com" #optional
#logoFile="bludphenomenon.png" #optional
#credits="Thanks to everyone who helped!" #optional
authors="Bludos" # Replace this with your actual name.
#displayTest="MATCH_VERSION" #optional

description='''
uh idk its secret you will know everything soon.
'''

[[dependencies.bludmod]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[43,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.bludmod]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]" # This specifies Minecraft 1.19.2.
ordering="NONE"
side="BOTH"